services:
  - docker

before_install:
  - docker build -t robertbeal/openconnect .

script:
  - docker run --rm --name openconnect --read-only --tmpfs /var/run/vpnc -e ARGS="-V" robertbeal/openconnect
